all: Exercise02_01 Exercise02_02 Exercise02_03 squeeze any setbits

Exercise02_01: Exercise02_01.c
	gcc -ansi -pedantic-errors -Wall -o Exercise02_01 Exercise02_01.c

Exercise02_02: Exercise02_02.c
	gcc -ansi -pedantic-errors -Wall -o Exercise02_02 Exercise02_02.c

Exercise02_03: Exercise02_03.c
	gcc -ansi -pedantic-errors -Wall -o Exercise02_03 Exercise02_03.c -lm

squeeze: Exercise02_04.c
	gcc -ansi -pedantic-errors -Wall -o squeeze Exercise02_04.c 

any: Exercise02_05.c
	gcc -ansi -pedantic-errors -Wall -o any Exercise02_05.c 

setbits: Exercise02_06.c
	gcc -ansi -pedantic-errors -Wall -o setbits Exercise02_06.c 
